services:
  backup:
    image: alpine:3.17.2
    container_name: registry_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - registry:/var/lib/registry
    restart: always

  registry:
    image: registry:2
    container_name: registry
    ports:
      - 8020:5000
    volumes:
      - registry:/var/lib/registry

volumes:
  registry: