services:
  backup:
    image: alpine:3.17.2
    container_name: standardnotes_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - logs:/var/lib/server/logs:ro
      - uploads:/opt/bundled/files/packages/files/dist/uploads:ro
      - mysql:/var/lib/mysql:ro
      - import:/docker-entrypoint-initdb.d:ro
      - redis:/data

  web:
    image: standardnotes/web:stable
    env_file: env.web
    container_name: standardnotes_web
    ports:
      - 8190:3001

  server:
    image: standardnotes/server
    env_file: env.server
    container_name: standardnotes_server
    ports:
      - 8191:3000
      - 8192:3104
    volumes:
      - logs:/var/lib/server/logs
      - uploads:/opt/bundled/files/packages/files/dist/uploads

  localstack:
    image: localstack/localstack:1.3
    container_name: standardnotes_localstack
    expose:
      - 4566
    restart: unless-stopped
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    volumes:
      - ./localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh

  db:
    image: mysql:8
    container_name: standardnotes_db
    env_file: env.db
    expose:
      - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql:/var/lib/mysql
      - import:/docker-entrypoint-initdb.d

  cache:
    image: redis:6.0-alpine
    container_name: standardnotes_redis
    volumes:
      - redis:/data
    expose:
      - 6379
    restart: unless-stopped

volumes:
  logs:
  uploads:
  mysql:
  import:
  redis: