services:
  backup:
    image: alpine:3.17.2
    container_name: mealie_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - data:/app/data
    restart: always

  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    expose:
      - 80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles

      # Default Recipe Settings
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - data:/app/data

volumes:
  data: