services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    env_file: env.n8n
    ports:
      - 8060:5678
    volumes:
      - data:/home/node/.n8n
    restart: unless-stopped

volumes:
  data: