services:
  backup:
    image: alpine:3.17.2
    container_name: miniflux_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  miniflux:
    image: miniflux/miniflux:2.0.42
    container_name: miniflux
    env_file: env.miniflux
    restart: always
    ports:
      - 8050:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: miniflux_db
    env_file: env.postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: