services:
  miniflux:
    image: miniflux/miniflux:2.0.47
    container_name: miniflux
    env_file: env.miniflux
    restart: unless-stopped
    ports:
      - 8050:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: miniflux_db
    env_file: env.postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: