services:
  vaultwarden:
    image: vaultwarden/server:1.29.1
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 8130:80
    volumes:
      - data:/data
    env_file: env.server

volumes:
  data: