services:
  vaultwarden:
    image: vaultwarden/server:1.28.0
    container_name: vaultwarden
    restart: always
    ports:
      - 8130:80
    volumes:
      - data:/data
    env_file: env.server

volumes:
  data: