services:
  backup:
    image: alpine:3.17.2
    container_name: vaultwarden_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - data:/data:ro
    restart: always

  vaultwarden:
    image: vaultwarden/server:1.28.0
    container_name: vaultwarden
    restart: always
    expose:
      - 80
    volumes:
      - data:/data
    env_file: env.server

volumes:
  data: