services:
  backup:
    image: alpine:3.17.2
    container_name: gitea_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - data:/data:ro
      - db:/var/lib/postgresql/data:ro
      - woodpecker:/var/lib/woodpecker:ro

  gitea:
    image: gitea/gitea:1.19.0
    container_name: gitea
    env_file: env.gitea
    restart: always
    volumes:
      - data:/data
    ports:
      - 8100:3000

  db:
    image: postgres:alpine
    container_name: gitea_db
    env_file: env.db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432

  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v0.15.7-alpine
    container_name: gitea_woodpecker
    restart: always
    env_file: env.woodpecker
    depends_on:
      - gitea
    expose:
      - 8101:8000
      - 8102:9000
    volumes:
      - woodpecker:/var/lib/woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v0.15.7-alpine
    container_name: gitea_woodpecker_agent
    env_file: env.woodpecker_agent
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

volumes:
  db:
  data:
  woodpecker: