services:
  backup:
    image: alpine:3.17.2
    container_name: mastodon_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - web:/mastodon/public/system:ro
      - redis:/data:ro
      - db:/var/lib/postgresql/data:ro

  db:
    image: postgres:14-alpine
    container_name: mastodon_db
    restart: always
    env_file: env.postgres
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'mastodon' ]
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mastodon_redis
    restart: always
    networks:
      - internal_network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
    volumes:
      - redis:/data

  web:
    image: tootsuite/mastodon:v4.1.3
    container_name: mastodon_web
    restart: always
    env_file: env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test:
        [
          'CMD-SHELL',
          'wget -q --spider --proxy=off localhost:3000/health || exit 1'
        ]
    ports:
      - 8012:3000
    depends_on:
      - db
      - redis
    volumes:
      - web:/mastodon/public/system
    extra_hosts:
      - "host.docker.internal:host-gateway"

  streaming:
    image: tootsuite/mastodon:v4.1.3
    container_name: mastodon_streaming
    restart: always
    env_file: env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      # prettier-ignore
      test:
        [
          'CMD-SHELL',
          'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1'
        ]
    ports:
      - 8013:4000
    depends_on:
      - db
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sidekiq:
    image: tootsuite/mastodon:v4.1.3
    container_name: mastodon_sidekiq
    restart: always
    env_file: env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: [ 'CMD-SHELL', "ps aux | grep '[s]idekiq 6' || false" ]
    volumes:
      - web:/mastodon/public/system

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  sidekiq:
  db:
  redis:
  web: