services:
  homepage:
    image: jordanroher/starbase-80:latest
    container_name: homepage
    ports:
      - 8090:4173
    restart: unless-stopped
    environment:
      - TITLE=Starbase 80
      - LOGO=/logo.png
    volumes:
        - ./config.json:/app/src/config.json
        - ./public/favicon.ico:/app/public/favicon.ico
        - ./public/logo.png:/app/public/logo.png
        - ./public/icons:/app/public/icons