version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:v0.6.10
    container_name: homepage
    ports:
      - 8090:3000
    volumes:
      - config:/app/config
      - //var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

volumes:
  config:
