services:
  web:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.starbase80.dev'
    env_file: env.gitlab
    ports:
      - 8280:80
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner:/etc/gitlab-runner

volumes:
  config:
  logs:
  data:
  runner: