version: '3.6'
services:
  web:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.starbase80.dev'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.starbase80.dev'
    ports:
      - 8280:80
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: '256m'

volumes:
  config:
  logs:
  data: