services:
  web:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.starbase80.dev'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/gitlab.rb')"
    ports:
      - 8280:80
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - runner:/etc/gitlab-runner:ro
      - ./gitlab.rb:/gitlab.rb:ro
    shm_size: '256m'

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab_runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner:/etc/gitlab-runner

volumes:
  config:
  logs:
  data:
  runner: