services:
  web:
    image: gitlab/gitlab-ee:15.10.2-ee.0
    restart: always
    hostname: starbase-80:8160
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'starbase-80:8160'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 8160:80
      - 8161:443
      - 8162:22
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    shm_size: 256m