services:
  grampsweb: &grampsweb
    container_name: grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - 8250:5000  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - users:/app/users  # persist user database
      - index:/app/indexdir  # persist search index
      - thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - cache:/app/cache  # persist export and report caches
      - secret:/app/secret  # persist flask secret
      - db:/root/.gramps/grampsdb  # persist Gramps database
      - media:/app/media  # persist media files
      - tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: always
    ports:
      - 8251:6379

volumes:
  users:
  index:
  thumb_cache:
  cache:
  secret:
  db:
  media:
  tmp: