services:
  backup:
    image: alpine:3.17.2
    container_name: trilium_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - trilium:/home/node/trilium-data
    restart: always

  trilium:
    image: zadam/trilium:0.59-latest
    container_name: trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - 8060:8080
    volumes:
      - trilium:/home/node/trilium-data

volumes:
  trilium: