services:
  backup:
    image: alpine:3.17.2
    container_name: vscode_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - config:/config:ro
    restart: always

  vscode:
    image: linuxserver/code-server:4.11.0
    container_name: vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - config:/config
    ports:
      - 8120:8443
    restart: always

volumes:
  config: