services:
  vscode:
    image: linuxserver/code-server:4.11.0
    container_name: vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - config:/config
    ports:
      - 8120:8443
    restart: always

volumes:
  config: