services:
  # editor:
  #   image: ubuntu:latest
  #   entrypoint: "tail -f /dev/null"
  #   restart: always
  #   volumes:
  #     - certbot:/var/www/certbot
  #     - letsencrypt:/etc/letsencrypt
    
  backup:
    image: alpine:3.17.2
    container_name: switchboard_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - certbot:/var/www/certbot:ro
      - grafana:/var/lib/grafana:ro
      - letsencrypt:/etc/letsencrypt:ro
      - logs:/var/log/nginx:ro
      - loki:/loki:ro
      - prometheus:/prometheus:ro

  nginx:
    image: nginx:1.23.3
    container_name: switchboard
    volumes:
      - ./sites:/etc/nginx/conf.d
      - logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
      - 8070:8070 # for prometheus
    restart: always
    networks:
      monitoring:
        ipv4_address: 10.10.10.10
        aliases:
          - nginx

  letsencrypt:
      image: certbot/certbot:v2.4.0
      container_name: switchboard_letsencrypt
      entrypoint: ""
      command: >
        sh -c "certbot certonly --reinstall -n -v -d notclickable.social -d www.notclickable.social --cert-name notclickable.social  --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com &&
        certbot certonly --reinstall -v -n -d notclickable.com -d www.notclickable.com --cert-name notclickable.com --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com &&
        certbot certonly --reinstall -v -n -d vaultwarden.notclickable.com --cert-name vaultwarden.notclickable.com --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com"
      depends_on:
          - nginx
      volumes:
          - letsencrypt:/etc/letsencrypt
          - certbot:/var/www/certbot
      environment:
          - TERM=xterm

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.11
    container_name: switchboard_status_exporter
    ports:
      - 8071:9113
    command:
      - -nginx.scrape-uri
      - http://10.10.10.10:8070/status
      - -web.telemetry-path=/metrics
    depends_on:
      - nginx
    restart: always
    networks:
      monitoring:
        ipv4_address: 10.10.10.20
        aliases:
          - exporter

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: switchboard_prometheus
    expose:
      - 9090
    depends_on:
      - nginx-prometheus-exporter
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      monitoring:
        ipv4_address: 10.10.10.30
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: switchboard_grafana
    ports:
      - 8072:3000
    depends_on:
      - prometheus
      - loki
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./loki-data-source.yml:/etc/grafana/provisioning/datasources/loki.yml
      - grafana:/var/lib/grafana
    networks:
      monitoring:
        ipv4_address: 10.10.10.40
        aliases:
          - grafana

  loki:
    image: grafana/loki:main-1c012d6
    container_name: switchboard_loki
    ports:
      - 3100
    volumes:
      - loki:/loki
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: 
      - '-config.file=/etc/loki/local-config.yml'
    depends_on:
      - nginx
    restart: always
    networks:
      monitoring:
        ipv4_address: 10.10.10.50
        aliases:
          - loki

  promtail:
    image: grafana/promtail:main-1c012d6
    container_name: switchboard_promtail
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - logs:/var/log/nginx
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    depends_on:
      - loki
    restart: always
    networks:
      monitoring:
        ipv4_address: 10.10.10.60
        aliases:
          - promtail

volumes:
  certbot:
  grafana:
  letsencrypt:
  logs:
  loki:
  prometheus:

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24