services:
  backup:
    image: alpine:3.17.2
    container_name: switchboard_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt:ro

  authelia:
    image: authelia/authelia:4.37.5
    container_name: switchboard_authelia
    restart: always
    environment:
      - TZ=America/Los_Angeles
    expose:
      - 9091
    volumes:
      - ./env.authelia_configuration.yml:/config/configuration.yml
      - ./env.authelia_users_database.yml:/config/users_database.yml
      - ./env.authelia_notification.txt:/config/notification.txt
      - authelia_logs:/logs
    network_mode: host

  redis:
    image: redis:alpine
    container_name: switchboard_authelia_redis
    security_opt:
      - no-new-privileges:true
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    command: redis-server --appendonly yes
    volumes:
      - authelia_redis:/data
    network_mode: host

  nginx:
    image: linuxserver/nginx
    container_name: switchboard
    volumes:
      - ./sites:/config/nginx/site-confs
      - ./snippets:/etc/nginx/snippets
      - logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    restart: always
    network_mode: host

  # Get one certificate
  letsencrypt_one:
    image: certbot/certbot:v2.4.0
    container_name: switchboard_letsencrypt_one
    entrypoint: ""
    command: >
      sh -c "certbot certonly --reinstall -n -v -d standardnotesfiles.starbase80.dev --cert-name standardnotesfiles.starbase80.dev  --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com"
    depends_on:
      - nginx
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    environment:
      - TERM=xterm

  # Renew certificates
  # letsencrypt:
  #   image: certbot/certbot:v2.4.0
  #   container_name: switchboard_letsencrypt
  #   entrypoint: ""
  #   command: >
  #     sh -c "certbot renew --keep-until-expiring -n -v"
  #   depends_on:
  #       - nginx
  #   volumes:
  #       - letsencrypt:/etc/letsencrypt
  #       - certbot:/var/www/certbot
  #   environment:
  #       - TERM=xterm

volumes:
  certbot:
  letsencrypt:
  logs:
  authelia_logs:
  authelia_redis: