services:
  backup:
    image: alpine:3.17.2
    container_name: switchboard_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - logs:/var/log/nginx:ro

  authelia:
    image: authelia/authelia:4.37.5
    container_name: switchboard_authelia
    restart: always
    environment:
      - TZ=America/Los_Angeles
    expose:
      - 9091
    volumes:
      - ./env.authelia_configuration.yml:/config/configuration.yml
      - ./env.authelia_users_database.yml:/config/users_database.yml
      - ./env.authelia_notification.txt:/config/notification.txt
      - authelia_logs:/logs
    networks:
      - net

  redis:
    image: redis:alpine
    container_name: switchboard_authelia_redis
    security_opt:
      - no-new-privileges:true
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    command: redis-server --appendonly yes
    volumes:
      - authelia_redis:/data
    networks:
      - net

  nginx:
    image: linuxserver/nginx
    container_name: switchboard
    volumes:
      - ./sites:/config/nginx/site-confs
      - ./snippets:/etc/nginx/snippets
      - logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
      - 8070:8070 # for prometheus
    restart: always
    networks:
      - net
      - archivebox_default
      - gitea_default
      - miniflux_default
      - rohertwins_default
      - mealie_default
      - vaultwarden_default
      - vscode_default
      - roherwiki_default
      - calibre_default
      - jellyfin_default
      - portainer_default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Get one certificate
  # letsencrypt_one:
  #   image: certbot/certbot:v2.4.0
  #   container_name: switchboard_letsencrypt_one
  #   entrypoint: ""
  #   command: >
  #     sh -c "certbot certonly --reinstall -n -v -d portainer.starbase80.dev --cert-name portainer.starbase80.dev  --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com"
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - letsencrypt:/etc/letsencrypt
  #     - certbot:/var/www/certbot
  #   environment:
  #     - TERM=xterm

  # Renew certificates
  # letsencrypt:
  #   image: certbot/certbot:v2.4.0
  #   container_name: switchboard_letsencrypt
  #   entrypoint: ""
  #   command: >
  #     sh -c "certbot renew --keep-until-expiring -n -v"
  #   depends_on:
  #       - nginx
  #   volumes:
  #       - letsencrypt:/etc/letsencrypt
  #       - certbot:/var/www/certbot
  #   environment:
  #       - TERM=xterm

volumes:
  certbot:
  letsencrypt:
  logs:
  authelia_logs:
  authelia_redis:

networks:
  net:
    external: true
  archivebox_default:
    external: true
  gitea_default:
    external: true
  miniflux_default:
    external: true
  rohertwins_default:
    external: true
  mealie_default:
    external: true
  vaultwarden_default:
    external: true
  vscode_default:
    external: true
  roherwiki_default:
    external: true
  calibre_default:
    external: true
  jellyfin_default:
    external: true
  portainer_default:
    external: true