services:
  nginx:
    image: nginx:1.23.3
    container_name: switchboard
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - mastodon_letsencrypt:/etc/letsencrypt-mastodon
      - calibre_letsencrypt:/etc/letsencrypt-calibre
      - miniflux_letsencrypt:/etc/letsencrypt-miniflux
      - archivebox_letsencrypt:/etc/letsencrypt-archivebox
      - notes_letsencrypt:/etc/letsencrypt-notes
    ports:
      - 80:80
      - 443:443
      - 8070:8070
    restart: always
    networks:
      - monitoring

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.11
    container_name: switchboard_exporter
    ports:
      - 8071:9113
    command:
      - -nginx.scrape-uri
      - http://127.0.0.1:8070
      - -web.telemetry-path=/metrics
    depends_on:
      - nginx
    restart: always
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: switchboard_prometheus
    expose:
      - 9090
    depends_on:
      - nginx-prometheus-exporter
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

volumes:
  prometheus:
  mastodon_letsencrypt:
    external: true
  calibre_letsencrypt:
    external: true
  miniflux_letsencrypt:
    external: true
  archivebox_letsencrypt:
    external: true
  notes_letsencrypt:
    external: true

networks:
  monitoring: