global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['10.10.10.30:9090']

  - job_name: 'nginx exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.10.10.20:8071']