---
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 65536
    write: 65536

log:
  level: info
  file_path: /logs/authelia.log
  format: json
  keep_stdout: true

theme: light

jwt_secret: SAMPLE_SECRET
default_redirection_url: https://auth.notclickable.com

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

authentication_backend:
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control:
  default_policy: deny
  networks:
  - name: internal
    networks:
    - 192.168.1.0/24
    - 10.0.3.2/24
  rules:
    #- domain: "*.mydomain.work"
    #  policy: bypass
    #  networks:
    #    - internal
    - domain: "*.notclickable.com"
      policy: one_factor

session:
  name: authelia_session
  secret: SAMPLE_SECRET
  expiration: 30d  # 1 h
  inactivity: 5d  # 5 day
  domain: notclickable.com  # Should match whatever your root protected domain is
  remember_me_duration:  30d
  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 5
  find_time: 120m
  ban_time: 300m

storage:
  encryption_key: SAMPLE_SECRET
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

ntp:
  address: "192.168.1.1:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false