---
server:
  host: 0.0.0.0
  port: 9091
  buffers:
    read: 65536
    write: 65536

log:
  level: info
  file_path: /logs/authelia.log
  format: json
  keep_stdout: true

theme: light

jwt_secret: SECRET
default_redirection_url: https://auth.starbase80.dev

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
      
access_control:
  default_policy: deny
  networks:
  - name: internal
    networks:
    - 192.168.1.0/24
  rules:
    - domain: "*.starbase80.dev"
      policy: bypass
      networks:
        - internal
    - domain: "*.starbase80.dev"
      policy: bypass
      resources:
      - '^/favicon.ico$'
      - '^/apple-touch-icon.png$'
      - '^/apple-touch-icon-precomposed.png$'
    - domain: metube.starbase80.dev
      policy: bypass
      resources:
      - '^/favicon/.*$'
    - domain: jellyfin.starbase80.dev
      policy: bypass
      resources:
      - '^/web/.*$'
    - domain: miniflux.starbase80.dev
      policy: bypass
      resources:
      - '^/accounts/ClientLogin$'
      - '^/reader/api.*$'
    - domain: woodpecker.starbase80.dev
      policy: bypass
      resources:
      - '^/web-config.js$'
      - '^/hook.*$'
    - domain: git.starbase80.dev
      policy: bypass
      resources:
      - '^/web-config.js$'
      - '^/login/oauth/.*$'
      - '^/api/.*$'
      - '^.*\.git.*$'
    - domain: portainer.starbase80.dev
      policy: bypass
      resources:
      - '^/Public/.*$'
      - '^/static/.*$'
    - domain: standardnotesserver.starbase80.dev
      policy: bypass
    - domain: standardnotesfiles.starbase80.dev
      policy: bypass
    - domain: shamir.starbase80.dev
      policy: bypass
    - domain: outline.starbase80.dev
      policy: bypass
    - domain: "*.starbase80.dev"
      policy: one_factor

session:
  name: authelia_session
  secret: SECRET
  expiration: 30d  # 1 h
  inactivity: 5d  # 5 day
  domain: starbase80.dev  # Should match whatever your root protected domain is
  remember_me_duration:  30d
  redis:
    host: localhost
    port: 6379

regulation:
  max_retries: 5
  find_time: 120m
  ban_time: 300m

storage:
  encryption_key: SECRET
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

ntp:
  address: "192.168.1.1:123"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

# OIDC config for Outline
identity_providers:
  oidc:
    hmac_secret: SECRET
      -----BEGIN CERTIFICATE-----
      SECRET
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      SECRET
      -----END CERTIFICATE-----
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      SECRET
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - https://outline.starbase80.dev
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: outline
        description: Outline
        secret: 'SECRETSECRETSECRET'
        sector_identifier: ''
        public: false
        authorization_policy: one_factor
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - https://outline.starbase80.dev/auth/oidc.callback
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none