services:
  backup:
    image: alpine:3.17.2
    container_name: calibre_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - config:/config:ro
      - letsencrypt:/etc/letsencrypt:ro
      - letsencrypt_lib:/var/lib/letsencrypt:ro
    restart: always

  calibre:
    image: linuxserver/calibre-web:0.6.19
    container_name: calibre_web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - config:/config
      - C:\Apps\Calibre:/library
    ports:
      - 8040:8083
    restart: unless-stopped

  nginx:
    image: nginx:1.23.3
    container_name: calibre_nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    ports:
      - 8041:80
      - 8042:443
    depends_on:
      - calibre
    restart: always

  letsencrypt:
    image: certbot/certbot:v2.4.0
    container_name: calibre_letsencrypt
    command: sh -c "certbot certonly --reinstall -v -d calibre.notclickable.com --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com"
    entrypoint: ""
    depends_on:
      - nginx
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
      - letsencrypt_lib:/var/lib/letsencrypt
    environment:
      - TERM=xterm

volumes:
  config:
  certbot:
  letsencrypt:
  letsencrypt_lib: