services:
  backup:
    image: alpine:3.17.2
    container_name: calibre_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - config:/config:ro
    restart: always

  calibre:
    image: linuxserver/calibre-web:0.6.19
    container_name: calibre_web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - config:/config
      - C:\Apps\Calibre:/library
    ports:
      - 8040:8083
    restart: unless-stopped

volumes:
  config: