services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    env_file: ./env.outline
    ports:
      - 8210:3000
    restart: always
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    container_name: outline_redis
    ports:
      - 8212:6379
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    container_name: outline_postgres
    ports:
      - 8213:5432
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file: env.outline

  storage:
    image: minio/minio
    container_name: outline_minio
    env_file: env.minio
    ports:
      - 8211:9000
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data:
  db: