services:
  backup:
    image: alpine:3.17.2
    container_name: outline_backup
    entrypoint: "tail -f /dev/null"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data:ro
      - data:/var/lib/outline/data:ro

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    env_file: ./env.outline
    ports:
      - 8210:3000
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - data:/var/lib/outline/data

  redis:
    image: redis
    container_name: outline_redis
    ports:
      - 8212:6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:15
    container_name: outline_postgres
    ports:
      - 8213:5432
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file: env.postgres

volumes:
  data:
  db: