services:
  trilium:
    image: zadam/trilium:0.59-latest
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - 8060:8080
    volumes:
      - trilium:/home/node/trilium-data

volumes:
  trilium: