services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: "host"
    volumes:
      - config:/config
      - cache:/cache
      - /mnt/synology/video:/video:ro
      - /mnt/synology/manga:/manga:ro
      - /mnt/synology/downloads/Calibre:/calibre:ro
    restart: always
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.starbase80.dev
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cache:
  config:
