services:
  backup:
    image: alpine:3.17.2
    container_name: minecraft_backup
    entrypoint: "tail -f /dev/null"
    restart: always
    volumes:
      - data:/data

  minecraft:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    ports:
      - "19132:19132/udp"
    volumes:
      - data:/data

volumes:
  data: