services:
  backup:
    image: alpine:3.17.2
    container_name: archivebox_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - data:/data
    restart: always

  archivebox:
    image: archivebox/archivebox:sha-829e377
    container_name: archivebox
    command: server --quick-init 0.0.0.0:8000
    ports:
        - 8020:8000
    environment:
        - ALLOWED_HOSTS=*
        - MEDIA_MAX_SIZE=750m
    volumes:
        - data:/data
    restart: always

volumes:
  data: