services:
  backup:
    image: alpine:3.17.2
    container_name: archivebox_backup
    entrypoint: "tail -f /dev/null"
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt:ro
      - letsencrypt_lib:/var/lib/letsencrypt:ro
    restart: always

  archivebox:
    image: archivebox/archivebox:sha-829e377
    container_name: archivebox
    command: server --quick-init 0.0.0.0:8000
    ports:
        - 8020:8000
    environment:
        - ALLOWED_HOSTS=*
        - MEDIA_MAX_SIZE=750m
    volumes:
        - data:/data

  nginx:
    image: nginx:1.23.3
    container_name: archivebox_nginx
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - letsencrypt:/etc/letsencrypt
        - certbot:/var/www/certbot
    ports:
        - 8021:80
        - 8022:443
    depends_on:
        - archivebox
    restart: always

  letsencrypt:
    image: certbot/certbot:v2.4.0
    container_name: archivebox_letsencrypt
    command: sh -c "certbot certonly --reinstall -v -d archivebox.notclickable.com --webroot --webroot-path /var/www/certbot/ --agree-tos --email jordan@notclickable.com"
    entrypoint: ""
    depends_on:
        - nginx
    volumes:
        - letsencrypt:/etc/letsencrypt
        - certbot:/var/www/certbot
        - letsencrypt_lib:/var/lib/letsencrypt
    environment:
        - TERM=xterm

volumes:
  data:
  certbot:
  letsencrypt:
  letsencrypt_lib: