services:
  metube:
    image: alexta69/metube:2023-03-05
    container_name: metube
    restart: always
    environment:
      - YTDL_OPTIONS={"format":"bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4","cookiefile":"/cookies/cookies.txt"}
    expose:
      - 8081
    volumes:
      - /mnt/synology/video/YouTube:/downloads
      # - ./env.cookies:/cookies/cookies.txt