services:
  metube:
    image: alexta69/metube:2023-03-05
    container_name: metube
    restart: always
    environment:
      - YTDL_OPTIONS={"format":"bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"}
    ports:
      - 8080:8081
    volumes:
      - ./downloads:/downloads