services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      # - YTDL_OPTIONS={"format":"bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4","cookiefile":"/cookies/cookies.txt"}
      - YTDL_OPTIONS={"format":"bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"}
    ports:
      - 8080:8081
    volumes:
      - /mnt/synology/video/YouTube:/downloads
      # - ./env.cookies:/cookies/cookies.txt