---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Personal:
    - Amazon:
        - abbr: AM
          icon: amazon
          href: https://amazon.com/

    - ChatGPT:
        - abbr: CG
          icon: mdi-chat
          href: http://chat.openai.com/

    - iCloud:
        - abbr: IC
          icon: mdi-apple
          href: https://www.icloud.com/

    - Facebook:
        - abbr: FB
          icon: facebook
          href: https://facebook.com/

    - Outlook:
        - abbr: OL
          icon: mdi-email-outline
          href: https://outlook.live.com/mail/inbox

- Developer:

    - AWS:
        - abbr: AW
          icon: aws
          href: https://aws.amazon.com/

    - GitHub:
        - abbr: GH
          icon: github
          href: https://github.com/

    - Hacker News:
        - abbr: HN
          icon: mdi-developer-board
          href: https://news.ycombinator.com/

    - Proxmox:
        - abbr: PX
          icon: proxmox
          href: https://proxmox:8006/

- Entertainment:

    - Disney+:
        - abbr: DS
          icon: mdi-rodent
          href: https://disneyplus.com/

    - HBO Max:
        - abbr: HM
          icon: mdi-movie-roll
          href: https://hbomax.com/

    - Jellyfin:
        - abbr: JF
          icon: jellyfin
          href: http://starbase-80:8030/

    - Netflix:
        - abbr: NF
          icon: netflix
          href: https://netflix.com/
    
    - Paramount+:
        - abbr: PP
          icon: mdi-star-three-points
          href: https://paramountplus.com/

    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com/