---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Services:
    - Archivebox:
        icon: /icons/archivebox.jpg
        href: https://archivebox.starbase80.dev/
        description: Backup webpages
        container: archivebox

    - Calibre:
        icon: calibre
        href: https://calibre.starbase80.dev/
        description: Ebook library
        container: calibre

    - Gitea:
        icon: /icons/gitea.svg
        href: https://git.starbase80.dev/
        description: Code hosting
        container: gitea

    # - Grafana:
    #     icon: /icons/grafana.jpg
    #     href: https://grafana.starbase80.dev/
    #     description: nginx dashboard
    #     container: switchboard

    - Jellyfin:
        icon: /icons/jellyfin.svg
        href: https://jellyfin.starbase80.dev/
        description: Media server

    - Mastodon:
        icon: /icons/mastodon.jpg
        href: https://notclickable.social/
        description: NotClickable.social
        container: mastodon_web

    - Mealie:
        icon: /icons/mealie.jpg
        href: https://mealie.starbase80.dev/
        description: Recipe manager
        container: mealie

    - N8N:
        icon: /icons/n8n.jpg
        href: https://n8n.starbase80.dev/
        description: Workflow automation
        container: n8n

    - MeTube:
        icon: /icons/metube.jpg
        href: https://metube.starbase80.dev/
        description: Archive YouTube
        container: metube

    - Miniflux:
        icon: /icons/miniflux.jpg
        href: https://miniflux.starbase80.dev/
        description: RSS server
        container: miniflux

    - Portainer:
        icon: portainer
        href: https://portainer.starbase80.dev/
        description: Docker management
        container: portainer

    - Roher Twins:
        icon: /icons/ghost.jpg
        href: https://rohertwins.starbase80.dev/
        description: Weekly newsletter
        container: rohertwins

    - Roher Wiki:
        icon: /icons/wikijs.svg
        href: https://roherwiki.starbase80.dev/
        description: Private wiki
        container: roherwiki

    - Vaultwarden:
        icon: /icons/vaultwarden.svg
        href: https://vaultwarden.starbase80.dev/
        description: Password manager
        container: vaultwarden

    - Visual Studio Code:
        icon: /icons/vscode.jpg
        href: https://vscode.starbase80.dev/
        description: Code editing
        container: vscode

    - Woodpecker:
        icon: /icons/woodpecker.jpg
        href: https://woodpecker.starbase80.dev/
        description: Continuous integration
        container: gitea_woodpecker

- Devices:

    - Router:
        icon: router
        href: http://192.168.1.1
        description: Netgear Orbi

    - Home Assistant:
        icon: /icons/home-assistant.svg
        href: http://homeassistant.local:8123/
        description: Home automation

    - Synology:
        icon: synology
        href: http://synology:5000
        description: NAS