---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Services:
    - Archivebox:
        icon: archivebox
        href: http://starbase-80:8020/
        description: Backup webpages
        container: archivebox

    - Bookstack:
        icon: bookstack
        href: http://starbase-80:8120/
        description: Private wiki
        container: bookstack

    - Calibre:
        icon: calibre
        href: http://starbase-80:8040/
        description: eBook reader
        container: calibre_web

    - Gitea:
        icon: gitea
        href: http://starbase-80:8100/
        description: Git server
        container: gitea

    - Home Assistant:
        icon: home-assistant
        href: http://homeassistant.local:8123/
        description: Home automation

    - Mealie:
        icon: mealie
        href: http://starbase-80:8110/
        description: Recipe manager
        container: mealie

    - MeTube:
        icon: metube
        href: http://starbase-80:8080/
        description: YouTube archiver
        container: metube

    - nginx:
        icon: grafana
        href: http://starbase-80:8072/
        description: nginx Switchboard
        container: switchboard

    - Miniflux:
        icon: miniflux
        href: http://starbase-80:8050/
        description: RSS server
        container: miniflux

    - NotClickable.social:
        icon: mastodon
        href: https://notclickable.social/
        description: Mastodon instance
        container: mastodon_web

    - Standard Notes:
        icon: standard-notes
        href: http://starbase-80:8060/
        description: Personal knowledge base
        container: standardnotes

- Devices:

    - Proxmox:
        icon: proxmox
        href: https://proxmox:8006/
        description: Virtualization host

    - Synology:
        icon: synology
        href: https://192.168.1.3:5001/
        description: NAS

- Games:

    - Minecraft:
        icon: minecraft
        href: https://www.minecraft.net/
        description: 192.168.1.57:19132
        container: minecraft