---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Services:
    - Archivebox:
        icon: /icons/archivebox.jpg
        href: http://starbase-80:8020/
        description: Backup webpages
        container: archivebox

    - Calibre:
        icon: /icons/calibre.jpg
        href: http://starbase-80:8040/
        description: eBook reader
        container: calibre_web

    - Gitea:
        icon: /icons/gitea.jpg
        href: http://starbase-80:8100/
        description: Code hosting and CI/CD
        container: gitea

    - Mealie:
        icon: mealie
        href: http://starbase-80:8110/
        description: Recipe manager
        container: mealie

    - MeTube:
        icon: metube
        href: http://starbase-80:8080/
        description: Archive YouTube
        container: metube

    - Grafana:
        icon: grafana
        href: http://starbase-80:8072/
        description: nginx dashboard
        container: switchboard

    - Jellyfin:
        icon: /icons/jellyfin.svg
        href: http://starbase-80:8030/
        description: Media server

    - Mastodon:
        icon: mastodon
        href: https://notclickable.social/
        description: NotClickable.social
        container: mastodon_web

    - Minecraft:
        icon: minecraft
        href: http://192.168.1.57
        description: Bedrock server
        container: minecraft

    - Miniflux:
        icon: miniflux
        href: http://starbase-80:8050/
        description: RSS server
        container: miniflux

    - Vaultwarden:
        icon: /icons/vaultwarden.svg
        href: https://vaultwarden.notclickable.com/
        description: Password manager
        container: vaultwarden

    - Visual Studio Code:
        icon: vscode
        href: http://starbase-80:8120
        description: Code editing
        container: vscode

    - WikiJS:
        icon: /icons/wikijs.svg
        href: http://starbase-80:8060/
        description: Private wiki
        container: wikijs

- Devices:

    - Home Assistant:
        icon: /icons/home-assistant.svg
        href: http://homeassistant.local:8123/
        description: Home automation

    - Router:
        icon: router
        href: http://192.168.1.1
        description: Netgear Orbi

    - Synology:
        icon: synology
        href: http://synology:5000
        description: NAS