---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Services:
    - Archivebox:
        icon: /icons/archivebox.jpg
        href: http://starbase-80:8020/
        description: Backup webpages
        container: archivebox

    - Ghost:
        icon: /icons/ghost.jpg
        href: http://starbase-80:8150/
        description: The Roher Twins
        container: roher_twins

    - Gitea:
        icon: /icons/gitea.svg
        href: http://starbase-80:8100/
        description: Code hosting
        container: gitea

    - Grafana:
        icon: /icons/grafana.jpg
        href: http://starbase-80:8072/
        description: nginx dashboard
        container: switchboard

    - Jellyfin:
        icon: /icons/jellyfin.svg
        href: http://starbase-80:8030/
        description: Media server

    - Mastodon:
        icon: /icons/mastodon.jpg
        href: https://notclickable.social/
        description: NotClickable.social
        container: mastodon_web

    - Mealie:
        icon: /icons/mealie.jpg
        href: http://starbase-80:8110/
        description: Recipe manager
        container: mealie

    - N8N:
        icon: /icons/n8n.jpg
        href: http://starbase-80:8140/
        description: Workflow automation
        container: n8n

    - MeTube:
        icon: /icons/metube.jpg
        href: http://starbase-80:8080/
        description: Archive YouTube
        container: metube

#    - Minecraft:
#        icon: /icons/minecraft.jpg
#        href: http://192.168.1.57
#        description: 192.168.1.3 (Bedrock)
#        container: minecraft

    - Miniflux:
        icon: /icons/miniflux.jpg
        href: http://starbase-80:8050/
        description: RSS server
        container: miniflux

    - Vaultwarden:
        icon: /icons/vaultwarden.svg
        href: https://vaultwarden.notclickable.com/
        description: Password manager
        container: vaultwarden

    - Visual Studio Code:
        icon: /icons/vscode.jpg
        href: http://starbase-80:8120
        description: Code editing
        container: vscode

    - WikiJS:
        icon: /icons/wikijs.svg
        href: http://starbase-80:8060/
        description: Private wiki
        container: wikijs

    - Woodpecker:
        icon: /icons/woodpecker.jpg
        href: http://starbase-80:8101/
        description: Continuous integration
        container: gitea_woodpecker

- Devices:

    - Router:
        icon: router
        href: http://192.168.1.1
        description: Netgear Orbi

    - Home Assistant:
        icon: /icons/home-assistant.svg
        href: http://homeassistant.local:8123/
        description: Home automation

    - Synology:
        icon: synology
        href: http://synology:5000
        description: NAS