---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Not Clickable
theme: light
color: gray
hideVersion: true
favicon: /icons/not-clickable.ico

layout:
  Services:
    style: row
    columns: 4
  Devices:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
