---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Starbase 80
theme: light
color: gray
hideVersion: true
favicon: /icons/favicon.ico

layout:
  Services:
    style: row
    columns: 4
  Devices:
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
